import Head from 'next/head';
import Box from '@mui/system/Box';

import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { cities } from '../../lib/data';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  console.log(cities);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {cities?.map((city, i) => (
          <>{city?.name}</>
        ))}
      </main>
    </>
  );
}
